### ISSUE TITLE
Fails to load on windows 11

### ISSUE THREAD

**Issue by KubaPro010** [FiendChain/SDRPlusPlus-DAB-Radio-Plugin#3]
Im using SDRPlusPlus 1.1.0, i dont have avx or avx2 (yes ik old cpu but socket has no avx cpus and im not that rich,i wanna buy other stuff) instead of actually working, it doesnt show up in the modules menu after checking the console i see this: `[22/01/2024 21:09:45.000] [ERROR] Couldn't load C:/SDRPlusPlus/modules/dab_plugin.dll. Error code: 1114`

**Comment by KubaPro010** [comment]
Why have this crappy compiling system in the first place? i checked toolchains/windows and i saw that i need to execute sh files? on windows? i tried to execute them with mingw's sh executable, but it requires ninja too, cmake didnt recognize ninja, but i had it installed, still theres no any build.ninja's (note: that im not familliar with ninja and how it works and why does it even exist when cmake and make do the job), take a example on dbdexter's radiosonde plugin compilation, easy to compile with sdr++, but here with this crap compile is hard, i hope this helps :)

**Comment by KubaPro010** [comment]
:)

**Comment by williamyang98** [comment]
I've built the plugin for SSE2 from this commit [f726096](https://github.com/FiendChain/SDRPlusPlus-DAB-Radio-Plugin/tree/f72609640d7a6f6777064503e580c9811a7a11d7). Apologies for the unclear instructions.

Download page: [dab_plugin_windows_x64_sse2](https://github.com/williamyang98/SDRPlusPlus-DAB-Radio-Plugin/releases/tag/v1.1.0). The included ```fftw3.dll``` has SSE2 only instructions, but probably doesn't need to be copied into your installation of SDR++. 

Here are the improved instructions for Windows if you are interested in building from source: [README.md](https://github.com/williamyang98/SDRPlusPlus-DAB-Radio-Plugin/blob/08002d1cf9684328437aec58a9d2624d95f31eac/toolchains/windows/README.md). The only change absolutely required to compile with SSE2 instructions is to remove the ```/arch:AVX2``` flag in ```CMakePresets.txt```. Optionally, if fftw3 is using unsupported instructions, you can modify ```vcpkg.json``` so it uses ```"features": ["sse2"]```, but this shouldn't be necessary.

I've improved the build instructions so it doesn't specify Ninja. The .sh files are supposed to be executed by git-bash which is installed alongside git on Windows, but we can manually run the build commands inside the Visual Studio C++ cmd developer enviroment. The build environment does not use mingw or msys, the requirements are Visual Studio C++, vcpkg and python >= 3.4. Ninja is used optionally as the buildsystem since it parallelises builds and avoids excessive recompiles on changes better than MSBuild on my system.

All feedback is welcomed if there are other problems or ambiguities in the README.md build instructions.

**Comment by KubaPro010** [comment]
Tested it now, seems to work fine, tuned into the local DAB broadcaster and audio and everything seems to work, will probably try to compile it, anyways, thanks!
